---
branches:
  only:
    - master

sudo: required

services:
  - docker

before_script:
  - docker build --no-cache -t ansible-roles-test tests/support

script:
  - >
    docker run -it
    -v $PWD:/etc/ansible/roles/route53
    --env AWS_ACCESS_KEY=$AWS_ACCESS_KEY
    --env AWS_SECRET_KEY=$AWS_SECRET_KEY
    --env AWS_REGION=$AWS_REGION
    --workdir /etc/ansible/roles/route53/tests
    ansible-roles-test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
